# Generated by Django 3.1.6 on 2021-04-10 12:37

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import test_check.models


class Migration(migrations.Migration):

    dependencies = [
        ('test_check', '0002_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', jsonfield.fields.JSONField(default=test_check.models.defaults_url)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_check.city', verbose_name='Город')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_check.language', verbose_name='Язык программирования')),
            ],
            options={
                'unique_together': {('city', 'language')},
            },
        ),
    ]
